version: '3'
services:
  forms:
    build: forms/
    container_name: site-forms
    volumes:
      - ./forms/app:/src
    ports:
      - 8000:8000
  
  feed:
    build: feed/
    container_name: site-feed
    volumes:
      - "./feed/app:/src"
    ports:
      - 8100:8100

  api:
    build: api/
    container_name: site-api
    volumes:
      - ./api/app:/src
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - ADMIN_SITE=${ADMIN_SITE}
      - REDIS_URL=redis://cache
    ports:
      - 8200:8200
    links:
      - redis
      - wp
    networks:
      - app-network 

  redis:
    image: redis
    container_name: cache
    command: redis-server --requirepass ${REDIS_PASSWORD}
    expose:
      - 6379
    networks:
      - app-network
      
  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    env_file: .env
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=sh_db
    volumes: 
      - ./admin/db:/var/lib/mysql      
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wp:
    depends_on: 
      - db
    image: wordpress:latest
    container_name: wp
    restart: unless-stopped
    env_file: .env
    ports:
      - 8400:80
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - WORDPRESS_DB_NAME=sh_db
    volumes:
      - ./admin/app:/var/www/html
      - ./admin/config/php.conf.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - app-network
networks:
  app-network:
    driver: bridge 
