version: '3'
services:
  client:
    build: client/
    volumes:
      - ./client/app:/app
    environment:
      - ADMIN_SITE=${ADMIN_SITE}
      - CACHED_API=${CACHED_API}
      - FORMS_API=${FORMS_API}
      - FEED_API=${FEED_API}
    ports:
      - ${IP}:8500:81
    links:
      - wp
      - api
      - forms
      - feed

  forms:
    build: forms/
    volumes:
      - ./forms/app:/src
    ports:
      - ${IP}:8000:8000
  
  feed:
    build: feed/
    volumes:
      - "./feed/app:/src"
    ports:
      - ${IP}:8100:8100

  api:
    build: api/
    volumes:
      - ./api/app:/src
    env_file: .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - ADMIN_SITE=${ADMIN_SITE}
      - REDIS_URL=redis://cache
    ports:
      - ${IP}:8200:8200
    links:
      - redis
      - wp
    networks:
      - app-network
  

  redis:
    image: redis
    container_name: cache
    command: redis-server --requirepass ${REDIS_PASSWORD}
    expose:
      - 6379
    networks:
      - app-network
      
  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    env_file: .env
    ports:
      - ${IP}:3306:3306
    environment:
      - MYSQL_DATABASE=sh_db
    volumes: 
      - ./admin/db:/var/lib/mysql      
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wp:
    depends_on: 
      - db
    image: wordpress:latest
    container_name: wp
    restart: unless-stopped
    env_file: .env
    ports:
      - ${IP}:8400:80
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - WORDPRESS_DB_NAME=sh_db
    volumes:
      - ./admin/app:/var/www/html
      - ./admin/config/php.conf.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - app-network

  webserver:
    depends_on:
      - wp
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./admin/app:/var/www/html
      - ./client/app/dist:/usr/share/nginx/html
      - ./nginx/:/etc/nginx/conf.d
      # - certbot-etc:/etc/letsencrypt
    networks:
      - app-network

  # certbot:
  #   depends_on:
  #     - webserver
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - certbot-etc:/etc/letsencrypt
  #     - ./admin/app:/var/www/html
  #     - ./client/app/dist:/usr/share/nginx/html
  #   command: bash -c "certonly --webroot --webroot-path=/var/www/html --email ptumulty@sh-law.com --agree-tos --no-eff-email --force-renewal -d admin.scarincihollenbeck.cc -d www.admin.scarincihollenbeck.cc && certonly --webroot --webroot-path=/usr/share/nginx/html --email ptumulty@sh-law.com --agree-tos --no-eff-email --force-renewal -d scarincihollenbeck.cc -d www.scarincihollenbeck.cc"
  
volumes:
  certbot-etc:
networks:
  app-network:
    driver: bridge  
