version: '3'
services:
  # client:
  #   build: client/
  #   volumes:
  #     - "./client/app:/app"
  #     # - "./client/client.nginx.conf /etc/nginx/conf.d/client.nginx.confd"
  #   environment:
  #     - ADMIN_SITE=${ADMIN_SITE}
  #     - CACHED_API=${CACHED_API}
  #     - FORMS_API=${FORMS_API}
  #     - FEED_API=${FEED_API}
  #   ports:
  #     - ${IP}:8500:80
  #   links:
  #     - wp
  #     - api
  #     - forms
  #     - feed

  # forms:
  #   build: forms/
  #   volumes:
  #     - "./forms/app:/src"
  #   ports:
  #     - ${IP}:8000:8000
  
  # feed:
  #   build: feed/
  #   volumes:
  #     - "./feed/app:/src"
  #   ports:
  #     - ${IP}:8100:8100

  # api:
  #   build: api/
  #   volumes:
  #     - "./api/app:/src"
  #   environment:
  #     - REDIS_PASSWORD=${REDIS_PASSWORD}
  #     - ADMIN_SITE=${ADMIN_SITE}
  #     - REDIS_URL=redis://cache
  #   ports:
  #     - ${IP}:8200:8200
  #   links:
  #     - redis
  #     - wp

  # redis:
  #   image: redis
  #   container_name: cache
  #   command: redis-server --requirepass ${REDIS_PASSWORD}
  #   expose:
  #     - 6379
  
  wp:
    image: bitnami/wordpress-nginx:latest
    ports:
      - ${IP}:8400:80
      - ${IP}:8443:443
    volumes:
      - ./admin/config/php.conf.ini:/opt/bitnami/php/etc/php.ini
      - ./admin/config/php.conf.ini:/opt/bitnami/apps/wordpress/conf/php-fpm/php-settings.conf 
      - ./admin/wp-app:/bitnami/wordpress
      # - ./admin/default.conf:/opt/bitnami/nginx/conf/server_blocks/default.conf
    environment:      
      MARIADB_HOST: mariadb
      WORDPRESS_DATABASE_USER: sh_user
      WORDPRESS_DATABASE_NAME: sh_db
      ALLOW_EMPTY_PASSWORD: "yes"
      NAMI_LOG_LEVEL: trace
    depends_on:
      - mariadb
    links:
      - mariadb

  pma:
    image: phpmyadmin/phpmyadmin
    volumes:
      - ./admin/config/php.conf.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      - ${IP}:8300:80
    links:
      - mariadb:mariadb

  mariadb:
    image: bitnami/mariadb:latest
    ports:
      - ${IP}:3306:3306
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      MARIADB_USER: sh_user
      MARIADB_PASSWORD: sh_pass
      MARIADB_DATABASE: sh_db

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local